<br><br>
<?php
for ($i = 1; $i <= $num_years; $i++) {
    echo '<table class="table small">';
    echo '<tr><td colspan="2">Season Results Year ', $i, '</td><td>Vs</td><td>Home or Away</td><td>Score</td><td>Result</td><td>Divisional</td></tr>';
    echo '<tr>';
    echo '<td>Simulated Row</td>';
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Simulated', 'Week', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Simulated', 'Vs', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Simulated', 'HorA', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Simulated', 'Score', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Simulated', 'Result', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Simulated', 'Divisional', 'Team');
    echo '</tr>';
    echo '<tr>';
    echo '<td>Week 1</td>';
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 1', 'Week', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 1', 'Vs', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 1', 'HorA', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 1', 'Score', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 1', 'Result', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 1', 'Divisional', 'Team');
    echo '</tr>';
    echo '<td>Week 2</td>';
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 2', 'Week', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 2', 'Vs', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 2', 'HorA', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 2', 'Score', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 2', 'Result', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 2', 'Divisional', 'Team');
    echo '</tr>';
    echo '<td>Week 3</td>';
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 3', 'Week', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 3', 'Vs', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 3', 'HorA', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 3', 'Score', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 3', 'Result', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 3', 'Divisional', 'Team');
    echo '</tr>';
    echo '<td>Week 4</td>';
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 4', 'Week', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 4', 'Vs', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 4', 'HorA', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 4', 'Score', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 4', 'Result', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 4', 'Divisional', 'Team');
    echo '</tr>';
    echo '<td>Week 5</td>';
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 5', 'Week', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 5', 'Vs', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 5', 'HorA', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 5', 'Score', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 5', 'Result', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 5', 'Divisional', 'Team');
    echo '</tr>';
    echo '<td>Week 6</td>';
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 6', 'Week', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 6', 'Vs', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 6', 'HorA', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 6', 'Score', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 6', 'Result', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 6', 'Divisional', 'Team');
    echo '</tr>';
    echo '<td>Week 7</td>';
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 7', 'Week', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 7', 'Vs', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 7', 'HorA', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 7', 'Score', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 7', 'Result', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 7', 'Divisional', 'Team');
    echo '</tr>';
    echo '<td>Week 8</td>';
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 8', 'Week', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 8', 'Vs', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 8', 'HorA', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 8', 'Score', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 8', 'Result', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 8', 'Divisional', 'Team');
    echo '</tr>';
    echo '<td>Week 9</td>';
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 9', 'Week', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 9', 'Vs', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 9', 'HorA', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 9', 'Score', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 9', 'Result', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 9', 'Divisional', 'Team');
    echo '</tr>';
    echo '<td>Week 10</td>';
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 10', 'Week', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 10', 'Vs', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 10', 'HorA', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 10', 'Score', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 10', 'Result', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 10', 'Divisional', 'Team');
    echo '</tr>';
    echo '<td>Week 11</td>';
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 11', 'Week', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 11', 'Vs', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 11', 'HorA', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 11', 'Score', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 11', 'Result', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 11', 'Divisional', 'Team');
    echo '</tr>';
    echo '<td>Week 12</td>';
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 12', 'Week', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 12', 'Vs', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 12', 'HorA', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 12', 'Score', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 12', 'Result', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 12', 'Divisional', 'Team');
    echo '</tr>';
    echo '<td>Week 13</td>';
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 13', 'Week', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 13', 'Vs', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 13', 'HorA', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 13', 'Score', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 13', 'Result', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 13', 'Divisional', 'Team');
    echo '</tr>';
    echo '<td>Week 14</td>';
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 14', 'Week', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 14', 'Vs', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 14', 'HorA', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 14', 'Score', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 14', 'Result', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 14', 'Divisional', 'Team');
    echo '</tr>';
    echo '<td>Week 15</td>';
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 15', 'Week', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 15', 'Vs', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 15', 'HorA', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 15', 'Score', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 15', 'Result', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 15', 'Divisional', 'Team');
    echo '</tr>';
    echo '<td>Week 16</td>';
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 16', 'Week', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 16', 'Vs', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 16', 'HorA', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 16', 'Score', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 16', 'Result', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 16', 'Divisional', 'Team');
    echo '</tr>';
    echo '<td>Week 17</td>';
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 17', 'Week', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 17', 'Vs', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 17', 'HorA', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 17', 'Score', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 17', 'Result', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Week 17', 'Divisional', 'Team');
    echo '</tr>';
    echo '<td>Wildcard</td>';
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Wildcard', 'Week', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Wildcard', 'Vs', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Wildcard', 'HorA', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Wildcard', 'Score', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Wildcard', 'Result', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Wildcard', 'Divisional', 'Team');
    echo '</tr>';
    echo '<td>Divisional</td>';
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Divisional', 'Week', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Divisional', 'Vs', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Divisional', 'HorA', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Divisional', 'Score', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Divisional', 'Result', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Divisional', 'Divisional', 'Team');
    echo '</tr>';
    echo '<td>Conference</td>';
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Conference', 'Week', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Conference', 'Vs', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Conference', 'HorA', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Conference', 'Score', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Conference', 'Result', 'Team');
    echo checkInfoExists($fran, $i, 'results', 'Week', 'Conference', 'Divisional', 'Team');
    echo '</tr>';
    echo '</table>';
}
